# Generated by Django 5.0.2 on 2024-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djinni", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancydjinni",
            name="web_id",
        ),
        migrations.AddField(
            model_name="vacancydjinni",
            name="url",
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
