# Generated by Django 5.0.2 on 2024-03-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancydjinni",
            options={
                "verbose_name": "Vacancy Djinni",
                "verbose_name_plural": "Vacancies Djinni",
            },
        ),
    ]
