# Generated by Django 5.0.2 on 2024-03-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_boards", "0002_alter_vacancydjinni_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Name job board",
                "verbose_name_plural": "Name job boards",
            },
        ),
        migrations.DeleteModel(
            name="VacancyDjinni",
        ),
    ]
